apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
data:
  # --- Server ports ---
  SERVER_PORT: "8083"
  MANAGEMENT_SERVER_PORT: "8083"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"

  # --- Profiles ---
  SPRING_PROFILES_ACTIVE: "USER,k8s"

  # --- Datasource (Postgres) ---
  DATASOURCE_URL: "postgres:5432"
  DATASOURCE_DATABASE: "pgdb"
  DATASOURCE_USER: "pg"
  DATASOURCE_PASSWORD: "pgpass"

  # --- Hibernate ---
  SHOW_SQL: "false"

  # --- Logging ---
  LOGGING_LEVEL_PG: "debug"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "debug"

  # --- MongoDB ---
  MONGODB_HOST: "mongo"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "payments"

  # --- Remote modules (other microservices) ---
  CONTEXT_AUTH_HOST: "http://context-auth:8081"
  ACCOUNTS_HOST: "http://accounts:8082"

  # --- Kafka ---
  KAFKA_BOOTSTRAP_SERVER: "kafka:9092"

  # --- AWS S3 / MinIO ---
  PG_LIB_AWSFILES_BUCKET_NAME: "payments-imported-files"
  PG_LIB_AWSFILES_ACCESS_KEY: "minio"
  PG_LIB_AWSFILES_SECRET_KEY: "minio123"
  PG_LIB_AWSFILES_AWS_URL: "http://minio:9000"
