apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
data:
  # --- Server ports ---
  SERVER_PORT: "8083"
  MANAGEMENT_SERVER_PORT: "9083"

  # --- Profiles ---
  SPRING_PROFILES_ACTIVE: "USER"

  # --- Datasource (Postgres) ---
  DATASOURCE_URL: "postgres:5432"
  DATASOURCE_DATABASE: "mydb"
  DATASOURCE_USER: "pg"
  DATASOURCE_PASSWORD: "pgpass"

  # --- Hibernate ---
  SHOW_SQL: "false"

  # --- MongoDB ---
  MONGODB_HOST: "mongo"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "payments"

  # --- Remote modules (other microservices) ---
  CONTEXT_AUTH_HOST: "http://context-auth:80"
  ACCOUNTS_HOST: "http://accounts:80"

  # --- Kafka ---
  KAFKA_BOOTSTRAP_SERVER: "kafka:9092"

  # --- Distributed processing topics ---
  PG_KAFKA_CONSUMER_CONFIGS_PAYMENTS_MICROSERVICE_CHUNK_REQUEST_PROCESSING_BATCH_TOPIC_CONCURRENCY: "6"
  PG_KAFKA_TOPICS_0_TOPIC_NAME: "payments-microservice-chunk-request-processing-batch-topic"
  PG_KAFKA_TOPICS_0_TOPIC_PARTITIONS: "24"
  PG_KAFKA_TOPICS_0_TOPIC_REPLICATION_FACTOR: "1"

  PG_KAFKA_CONSUMER_CONFIGS_PAYMENTS_MICROSERVICE_CHUNK_REQUEST_IMPORTING_BATCH_TOPIC_CONCURRENCY: "6"
  PG_KAFKA_TOPICS_1_TOPIC_NAME: "payments-microservice-chunk-request-importing-batch-topic"
  PG_KAFKA_TOPICS_1_TOPIC_PARTITIONS: "24"
  PG_KAFKA_TOPICS_1_TOPIC_REPLICATION_FACTOR: "1"

  PG_KAFKA_CONSUMER_CONFIGS_PAYMENTS_MICROSERVICE_CHUNK_RESPONSE_PROCESSING_BATCH_TOPIC_CONCURRENCY: "12"
  PG_KAFKA_TOPICS_2_TOPIC_NAME: "payments-microservice-chunk-response-processing-batch-topic"
  PG_KAFKA_TOPICS_2_TOPIC_PARTITIONS: "48"
  PG_KAFKA_TOPICS_2_TOPIC_REPLICATION_FACTOR: "1"

  PG_KAFKA_CONSUMER_CONFIGS_PAYMENTS_MICROSERVICE_CHUNK_RESPONSE_IMPORTING_BATCH_TOPIC_CONCURRENCY: "12"
  PG_KAFKA_TOPICS_3_TOPIC_NAME: "payments-microservice-chunk-response-importing-batch-topic"
  PG_KAFKA_TOPICS_3_TOPIC_PARTITIONS: "48"
  PG_KAFKA_TOPICS_3_TOPIC_REPLICATION_FACTOR: "1"

  # --- Basic topics ---
  PG_KAFKA_CONSUMER_CONFIGS_PAYMENTS_MICROSERVICE_SCHEDULED_IMPORTS_PARSING_TOPIC_CONCURRENCY: "4"
  PG_KAFKA_TOPICS_4_TOPIC_NAME: "payments-microservice-scheduled-imports-parsing-topic"
  PG_KAFKA_TOPICS_4_TOPIC_PARTITIONS: "16"
  PG_KAFKA_TOPICS_4_TOPIC_REPLICATION_FACTOR: "1"

  PG_KAFKA_CONSUMER_CONFIGS_PAYMENTS_MICROSERVICE_REJECTED_IMPORTS_PARSING_TOPIC_CONCURRENCY: "4"
  PG_KAFKA_TOPICS_5_TOPIC_NAME: "payments-microservice-rejected-imports-parsing-topic"
  PG_KAFKA_TOPICS_5_TOPIC_PARTITIONS: "16"
  PG_KAFKA_TOPICS_5_TOPIC_REPLICATION_FACTOR: "1"

  PG_KAFKA_CONSUMER_CONFIGS_PAYMENTS_MICROSERVICE_IMPORTS_PARSING_FINISHED_TOPIC_CONCURRENCY: "4"
  PG_KAFKA_TOPICS_6_TOPIC_NAME: "payments-microservice-imports-parsing-finished-topic"
  PG_KAFKA_TOPICS_6_TOPIC_PARTITIONS: "16"
  PG_KAFKA_TOPICS_6_TOPIC_REPLICATION_FACTOR: "1"

  PG_KAFKA_CONSUMER_CONFIGS_PAYMENTS_MICROSERVICE_SCHEDULED_IMPORTS_IMPORTING_TOPIC_CONCURRENCY: "4"
  PG_KAFKA_TOPICS_7_TOPIC_NAME: "payments-microservice-scheduled-imports-importing-topic"
  PG_KAFKA_TOPICS_7_TOPIC_PARTITIONS: "16"
  PG_KAFKA_TOPICS_7_TOPIC_REPLICATION_FACTOR: "1"

  PG_KAFKA_CONSUMER_CONFIGS_PAYMENTS_MICROSERVICE_COMPLETED_IMPORTS_IMPORTING_TOPIC_CONCURRENCY: "4"
  PG_KAFKA_TOPICS_8_TOPIC_NAME: "payments-microservice-completed-imports-importing-topic"
  PG_KAFKA_TOPICS_8_TOPIC_PARTITIONS: "16"
  PG_KAFKA_TOPICS_8_TOPIC_REPLICATION_FACTOR: "1"

  PG_KAFKA_CONSUMER_CONFIGS_PAYMENTS_MICROSERVICE_REJECTED_IMPORTS_IMPORTING_TOPIC_CONCURRENCY: "4"
  PG_KAFKA_TOPICS_9_TOPIC_NAME: "payments-microservice-rejected-imports-importing-topic"
  PG_KAFKA_TOPICS_9_TOPIC_PARTITIONS: "16"
  PG_KAFKA_TOPICS_9_TOPIC_REPLICATION_FACTOR: "1"

  # --- AWS S3 / MinIO ---
  AWS_BUCKET_NAME: "payments-imported-files"
  AWS_ACCESS_KEY: "admin"
  AWS_SECRET_KEY: "admin123"
  AWS_URL: "http://minio:9000"
