apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 4
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: localhost:5000/pg.payments.standalone:1.0.0
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: payments-config

          volumeMounts:
            - name: payments-topics-config
              mountPath: /app/config

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: payments-topics-config
          configMap:
            name: payments-topics-config
