apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8083"
spec:
  selector:
    app: payments
  ports:
    - name: http
      port: 8083
      targetPort: 8083
