apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Accounts microservice
      - job_name: 'accounts'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['accounts:8082']

      # Payments microservice
      - job_name: 'payments'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['payments:8083']

      # Context-auth microservice
      - job_name: 'context-auth'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['context-auth:8081']

      # API Gateway
      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['api-gateway:8080']
