apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  # --- Server ---
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"

  # --- Remote microservices ---
  CONTEXT_AUTH_HOST: "http://context-auth:80"
  PAYMENTS_HOST: "http://payments:80"
