apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  # --- Server ---
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"

  # --- Remote microservices ---
  CONTEXT_AUTH_HOST: "http://context-auth:8081"
  PAYMENTS_HOST: "http://payments:8083"

  # --- Logging ---
  LOGGING_LEVEL_PG: "info"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "info"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "debug"
  LOGGING_FILE_NAME: ""
  LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{app-trace-id}] %-5level %logger{36} - %msg%n"

  # --- Gateway body size / multipart config ---
  SPRING_CODEC_MAX_IN_MEMORY_SIZE: "52428800"
  SPRING_CLOUD_GATEWAY_HTTPCLIENT_MAX_IN_MEMORY_SIZE: "52428800"
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "50MB"
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "50MB"
