apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-minio
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              echo "⏳ Waiting for MinIO at minio:9000..."
              until nc -z minio 9000; do
                sleep 2
              done
              echo "✅ MinIO is up!"
      containers:
        - name: create-bucket
          image: minio/mc
          command: ["/bin/sh", "-c"]
          args:
            - >
              /usr/bin/mc alias set myminio http://minio:9000 minio minio123 &&
              /usr/bin/mc mb -p myminio/payments-imported-files &&
              /usr/bin/mc anonymous set public myminio/payments-imported-files || true
      restartPolicy: OnFailure
