apiVersion: batch/v1
kind: Job
metadata:
  name: batch-schema-job
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              echo "⏳ Waiting for Postgres at postgres:5432..."
              until nc -z postgres 5432; do
                sleep 2;
              done
              echo "✅ Postgres is up!"
      containers:
        - name: apply-schema
          image: postgres:16
          command: ["sh", "-c"]
          args:
            - psql -h postgres -U pg -d pgdb -f /schema/schema-postgresql.sql
          env:
            - name: PGPASSWORD
              value: pgpass
          volumeMounts:
            - name: batch-schema
              mountPath: /schema
      restartPolicy: OnFailure
      volumes:
        - name: batch-schema
          configMap:
            name: spring-batch-schema
