apiVersion: v1
kind: ConfigMap
metadata:
  name: context-auth-config
data:
  # --- Server ports ---
  SERVER_PORT: "8081"
  MANAGEMENT_SERVER_PORT: "8081"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"

  # --- Datasource ---
  DATASOURCE_URL: "postgres:5432"
  DATASOURCE_DATABASE: "pgdb"
  DATASOURCE_USER: "pg"
  DATASOURCE_PASSWORD: "pgpass"

  # --- Hibernate ---
  SHOW_SQL: "false"
