apiVersion: v1
kind: ConfigMap
metadata:
  name: context-auth-config
data:
  # --- Server ports ---
  SERVER_PORT: "8081"
  MANAGEMENT_SERVER_PORT: "9081"

  # --- Datasource ---
  DATASOURCE_URL: "postgres:5432"
  DATASOURCE_DATABASE: "mydb"
  DATASOURCE_USER: "pg"
  DATASOURCE_PASSWORD: "pgpass"

  # --- Hibernate ---
  SHOW_SQL: "false"
