apiVersion: v1
kind: ConfigMap
metadata:
  name: context-auth-init-sql
data:
  context-auth-init.sql: |
    -- Insert admin user with bcrypt password (admin123)
    INSERT INTO users (id, username, password, enabled)
    VALUES ('00000000-0000-0000-0000-000000000001',
            'admin',
            '$2a$10$yk2YmM0jaHsP4SP2dbCF6O5zPzqgYimU/3U7b4PKn8fxEMsZwL.8e',
            true);

    -- Insert normal user with bcrypt password (user123)
    INSERT INTO users (id, username, password, enabled)
    VALUES ('00000000-0000-0000-0000-000000000002',
            'user',
            '$2a$10$5fR6UGN8iWkHq4snz6bSGOVa4b6JkF19jJp2prN7TZokQF6Mn3a3C',
            true);

    -- Assign roles (ADMIN, USER)
    INSERT INTO users_roles (user_entity_id, roles)
    VALUES ('00000000-0000-0000-0000-000000000001', 'ADMIN'),
           ('00000000-0000-0000-0000-000000000001', 'USER'),
           ('00000000-0000-0000-0000-000000000001', 'ACCOUNTANT'),
           ('00000000-0000-0000-0000-000000000002', 'USER'),
           ('00000000-0000-0000-0000-000000000002', 'ACCOUNTANT');
