apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers

  labels:
    grafana_dashboard: "1"
data:
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: 'Kubernetes'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
