version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg -d pgdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev   # login email
      PGADMIN_DEFAULT_PASSWORD: admin         # login password
    ports:
      - "39080:80"    # pgAdmin UI available at http://localhost:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
