apiVersion: v1
kind: Service
metadata:
  name: monitoring-prometheus-node-exporter

  labels:
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: monitoring
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: monitoring
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics