apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter

  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
      app.kubernetes.io/instance: monitoring
  namespaceSelector:
    matchNames: [ "monitoring" ]
  endpoints:
    - port: metrics
      interval: 15s
