---
apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kibana-init
          image: curlimages/curl:8.9.1
          command: ["/bin/sh", "/scripts/create-index-pattern.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: kibana-dataview